<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7d3b9b39c99287054b94a3f481e8da55
{
    public static $prefixLengthsPsr4 = array (
        'X' => 
        array (
            'XenditClient\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'XenditClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/xendit/xendit-php-clients/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7d3b9b39c99287054b94a3f481e8da55::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7d3b9b39c99287054b94a3f481e8da55::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
